### ISSUE TITLE
Tensorflow doesn't take advantage of queues and loading threads

### ISSUE THREAD

**Issue by Pyrestone** [wichtounet/frameworks#1]
Hi, The tensorflow implementation you've tested uses feed_dict, which is arguably one of the slowest ways to submit batches to GPU/CPU [source1](https://github.com/tensorflow/tensorflow/issues/2919),[source2](https://github.com/tensorflow/tensorflow/issues/3377#issuecomment-239969809). As a result the GPU idles for most of the training time, or in case of CPU training is busy loading batches. to overcome this issue, you can use a FIFOQueue with a separate data loading thread (C-thread, not python since that is still sequential).

Have a look at tensorflow's according QueueRunner classes. In my experience they can deliver more than 4x speedup if done correctly.

**Comment by wichtounet** [comment]
Hi @Pyrestone , 

It seemed to me that this was the default option to use Tensorflow. Every single TF example I've seen is using feed_dict. 

I'll try to investigate this. If there is a simple way to use this QueueRunner, I'll use it. But if I have to write complex Python code with threads myself, I'll not do it. The idea is to keep all the examples fairly simple. 

I'll let this open as I check some information about this. 

Thanks

**Comment by Pyrestone** [comment]
Hi @wichtounet,

Yes, this is the default option for Tensorflow, but it is not the most optimized for large datasets.

after all, the examples are for educational, not production purposes.
Good luck with the implementation!
