### ISSUE TITLE
Data obtention

### ISSUE THREAD

**Issue by hypnopump** [wichtounet/frameworks#2]
How did you get the data to train your experiments??

**Comment by wichtounet** [comment]
Hi, 

The data was obtained from the official sites of each dataset. 

For CIFAR-10 and MNIST, the different frameworks directly download the data from the official sites. As for ImageNET, I downloaded it myself on hard drive and resized them all by hand. For Caffe, they were transformed into LMDB. 

Do you need more precision ? 

Baptiste

**Comment by hypnopump** [comment]
Ohhhh, hearing that about the ImageNet dataset is truly discouraging... Anyway. thanks for the rapid response. Great work!

**Comment by wichtounet** [comment]
It's not really difficult, but it is fairly long and needs about 300 Go (if you count Caffe LMDB version) of storage.
