### ISSUE TITLE
wrong with while index < batch_size:

### ISSUE THREAD

**Issue by yao-ying** [wichtounet/frameworks#4]
Thank you for share the code.I leran a lot from the code.I think it should be 
while index <= batch_size:
if you use 
batch_size = 128
while index < batch_size:
each batch you only use 127 examples to train.
you can run a simple code to verify.

**Comment by wichtounet** [comment]
Thanks a lot for the report. You are right. 

I do not know why I set the index to 1 instead of zero 😢 

I will make the fix when I get the chance.

**Comment by yao-ying** [comment]
@wichtounet  not a big deal. Do you have a more efficient code to run ImageNet from scratch。Now I must do it。I think the total run time is terrible。What I known now is，if only have one gpu，It need one month。

**Comment by wichtounet** [comment]
Finally fixed 👍
